# Generated by Django 3.2.2 on 2021-07-26 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bouquet_name', models.CharField(max_length=100, verbose_name='꽃다발 이름')),
                ('total_price', models.IntegerField(verbose_name='꽃다발 총 가격')),
                ('bouquet_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('decorations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customizingapp.decoration')),
                ('flowers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customizingapp.flower')),
            ],
        ),
    ]
