# Generated by Django 3.2.2 on 2021-07-27 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customizingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wrapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrapper_name', models.CharField(max_length=100, null=True, verbose_name='포장지 이름')),
                ('wrapper_price', models.IntegerField(null=True, verbose_name='포장지 가격')),
                ('wrappr_img', models.ImageField(null=True, upload_to='', verbose_name='포장지 이미지')),
            ],
        ),
        migrations.RemoveField(
            model_name='bouquet',
            name='decorations',
        ),
        migrations.RemoveField(
            model_name='bouquet',
            name='flowers',
        ),
        migrations.AddField(
            model_name='bouquet',
            name='decoration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customizingapp.decoration', verbose_name='꽃다발 데코'),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='flower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customizingapp.flower', verbose_name='꽃다발 꽃'),
        ),
        migrations.AddField(
            model_name='decoration',
            name='deco_img',
            field=models.ImageField(null=True, upload_to='', verbose_name='데코 이미지'),
        ),
        migrations.AddField(
            model_name='decoration',
            name='deco_name',
            field=models.CharField(max_length=100, null=True, verbose_name='데코 이름'),
        ),
        migrations.AddField(
            model_name='decoration',
            name='deco_price',
            field=models.IntegerField(null=True, verbose_name='데코 가격'),
        ),
        migrations.AddField(
            model_name='flower',
            name='flower_img',
            field=models.ImageField(null=True, upload_to='', verbose_name='꽃 이미지'),
        ),
        migrations.AddField(
            model_name='flower',
            name='flower_name',
            field=models.CharField(max_length=100, null=True, verbose_name='꽃 이름'),
        ),
        migrations.AddField(
            model_name='flower',
            name='flower_price',
            field=models.IntegerField(null=True, verbose_name='꽃 가격'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='bouquet_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='꽃다발 만든이'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='bouquet_name',
            field=models.CharField(max_length=100, null=True, verbose_name='꽃다발 이름'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='total_price',
            field=models.IntegerField(null=True, verbose_name='꽃다발 총 가격'),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='wrapper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customizingapp.wrapper', verbose_name='꽃다발 포장지'),
        ),
    ]
