# Generated by Django 3.2.2 on 2021-07-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizingapp', '0002_auto_20210727_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
