# Generated by Django 3.2.2 on 2021-07-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizingapp', '0003_auto_20210727_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='flower_color',
            field=models.CharField(max_length=100, null=True, verbose_name='꽃 색상'),
        ),
    ]
