# Generated by Django 3.2.6 on 2021-08-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizingapp', '0004_flower_flower_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bouquet',
            old_name='bouquet_creator',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='bouquet',
            old_name='bouquet_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='decoration',
            old_name='deco_price',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='decoration',
            old_name='deco_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='decoration',
            old_name='deco_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='flower',
            old_name='flower_color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='flower',
            old_name='flower_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='flower',
            old_name='flower_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='flower',
            old_name='flower_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='wrapper',
            old_name='wrappr_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='wrapper',
            old_name='wrapper_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='wrapper',
            old_name='wrapper_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='bouquet',
            name='decoration',
        ),
        migrations.RemoveField(
            model_name='bouquet',
            name='flower',
        ),
        migrations.RemoveField(
            model_name='bouquet',
            name='wrapper',
        ),
        migrations.AddField(
            model_name='bouquet',
            name='bouquet_canvas',
            field=models.TextField(null=True, verbose_name='꽃다발 이미지 캔버스 데이터'),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='bouquet_items',
            field=models.TextField(null=True, verbose_name='꽃다발 내부 아이템'),
        ),
    ]
